id: ID3F4ED61
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T22:56:35+00:00'
last_modified: '2022-06-08T08:39:11.312343+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16736
  title: དབུ་མ་ཤར་གསུམ་གྱི་སྟོང་ཐུན་ཕྱྭ་པས་མཛད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BF62:
      image_group_id: I1KG16780
      title: ''
      total_pages: 190
      order: 1
      base_file: BF62.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
