id: P009105
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16736
  title: དབུ་མ་ཤར་གསུམ་གྱི་སྟོང་ཐུན་ཕྱྭ་པས་མཛད་པ།
  author: ''
  volumes:
    699f213a5dc948d49048101cba05de8c:
      image_group_id: I1KG16780
      title: ''
      volume_number: 1
      total_pages: 190
