id: P009105
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-19 19:23:10.566483
source_metadata:
  id: bdr:W1KG16736
  title: དབུ་མ་ཤར་གསུམ་གྱི་སྟོང་ཐུན་ཕྱྭ་པས་མཛད་པ།
  author: ''
  volumes:
    699f213a5dc948d49048101cba05de8c:
      image_group_id: I1KG16780
      title: ''
      volume_number: 1
      total_pages: 190
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
